@tool
extends RefCounted

## Emitter layer 1: the output buffer, the sourcemap, and all mutable state.

var diagnostics: GateDiagnostics

var source_path: String = ""

var _out: PackedStringArray = []

var _map: Array[int] = []          ## output line -> source line

var _indent: int = 0

## Source lines with at least one blank above them. A presence flag, not a count:
## a function trailer already emits one blank, so "at least one here, never two" is
## the only rule stable in both directions.
var _blank_before: Dictionary = {}

var _pending_line_src: Array = []

var _coll_depth: int = 0


func set_source(src: String) -> void:
	_blank_before.clear()
	var lines: PackedStringArray = src.split("\n")
	for i in range(lines.size()):
		var j: int = i - 1
		var saw_blank: bool = false
		while j >= 0:
			var t: String = lines[j].strip_edges()
			if t == "":
				saw_blank = true
				j -= 1
				continue
			if t.begins_with("#"):
				j -= 1
				continue
			if _is_annotation_only_line(t):
				j -= 1
				continue
			break
		if saw_blank and j >= 0:
			_blank_before[i + 1] = true


static func _is_annotation_only_line(t: String) -> bool:
	if not t.begins_with("@"):
		return false
	var i: int = 1
	while i < t.length() and _is_name_char_out(t[i]):
		i += 1
	if i < t.length() and t[i] == "(":
		var depth: int = 0
		var quote: String = ""
		while i < t.length():
			if quote != "":
				if t[i] == "\\":
					i += 2
					continue
				if t[i] == quote:
					quote = ""
			elif t[i] == '"' or t[i] == "'":
				quote = t[i]
			elif t[i] == "(":
				depth += 1
			elif t[i] == ")":
				depth -= 1
				if depth == 0:
					i += 1
					break
			i += 1
	return t.substr(i).strip_edges() == ""


static func _is_name_char_out(c: String) -> bool:
	return ((c >= "a" and c <= "z") or (c >= "A" and c <= "Z")
		or (c >= "0" and c <= "9") or c == "_")


func _blank_gap(src_line: int) -> void:
	if not _blank_before.has(src_line):
		return
	_blank_line(src_line)


func _blank_line(src_line: int) -> void:
	if _out.is_empty() or _out[_out.size() - 1].strip_edges() == "":
		return
	_out.append("")
	_map.append(src_line)

var _tmp: int = 0

var _pending: PackedStringArray = []

var _structs: Dictionary = {}

var _var_types: Dictionary = {}
var _var_depths: Dictionary = {}

var _struct_ops: Dictionary = {}

var _soa: Dictionary = {}

var _soa_cursors: Dictionary = {}

var _external_structs: Dictionary = {}

var _generics: Dictionary = {}          ## name -> ClassDecl with generic_params

var _instantiations: Dictionary = {}    ## mangled name -> [ClassDecl, {param: argname}]

var _subst: Dictionary = {}
var _subst_depth: Dictionary = {}
var _enum_names: Dictionary = {}
var _subst_types: Dictionary = {}

var _pending_generic: Dictionary = {}

var _declared_funcs: Dictionary = {}
var _func_returns: Dictionary = {}
var _cur_base: String = ""
var _cur_class: String = ""
var _class_bases: Dictionary = {}

var _needs_iface_helper: bool = false

var _interface_names: Dictionary = {}

var _overloads: Dictionary = {}   ## base name -> { arity -> mangled }
var _overload_owners: Dictionary = {}   ## base name -> { owning class name -> true }
var _erased_types: Dictionary = {}      ## interface/trait names, which have no runtime type

var _extern_origin: Dictionary = {}   ## declared name -> origin .gate path
var _extern_generics: Dictionary = {} ## generic name -> origin .gate path
var _used_origins: Dictionary = {}    ## origin .gate path -> const alias
var _self_path: String = ""       ## the file being compiled, which needs no preload
var _local_types: Dictionary = {}     ## type names this module declares itself
var _bound_names: Dictionary = {}     ## names that are a value in scope in this module
var _field_types: Dictionary = {}
var _var_dict_values: Dictionary = {}
var _project_generic_uses: Array = []
var _generic_renames: Dictionary = {}

var _in_namespace: bool = false

var _warned_narrow: bool = false

var _in_func_body: bool = false

var _scalar_repl: Dictionary = {}
var _scalar_names: Dictionary = {}

var _preload_targets: Dictionary = {}

## The first line of every generated file. The builder refuses to overwrite a `.gd`
## that does not carry it, so keep it first and keep its prefix stable.
const HEADER_MARKER := "# Generated by GATE"

const HEADER_LINES := [
	"# Generated by GATE from %s - do not edit.",
	"#",
	"# This file is transpiled output, not source. For as long as GATE is used in",
	"# this project, anything you change here is overwritten the next time",
	"# %s is compiled - edit that file instead.",
	"#",
	"# To stop using GATE for this script, delete the .gate file and this header;",
	"# what remains is ordinary GDScript you can maintain by hand.",
]


func _line(text: String, src_line: int) -> void:
	if text == "":
		_out.append("")
		_map.append(src_line)
		return
	if text.contains("\n"):
		var parts: PackedStringArray = text.split("\n")
		var srcs: Array = _pending_line_src
		_pending_line_src = []
		var use_srcs: bool = srcs.size() == parts.size() - 1
		_out.append("\t".repeat(_indent) + parts[0])
		_map.append(src_line)
		for i in range(1, parts.size()):
			_out.append(parts[i])
			_map.append(int(srcs[i - 1]) if use_srcs else src_line)
		return
	_pending_line_src = []
	_out.append("\t".repeat(_indent) + text)
	_map.append(src_line)


func _flush_pending(src_line: int) -> void:
	if _pending.is_empty():
		return
	var p: PackedStringArray = _pending
	_pending = PackedStringArray()
	for s in p:
		_line(s, src_line)


func _hoist(text: String) -> void:
	_pending.append(text)


func _new_tmp() -> String:
	while true:
		_tmp += 1
		var n: String = "__g%d" % _tmp
		if not _bound_names.has(n):
			return n
	return ""


func _emit_iface_helper() -> void:
	var saved: int = _indent
	_indent = 0
	_blank_line(1)
	_line("static func __gate_is(o, iface: String) -> bool:", 1)
	_indent = 1
	_line("if o == null:", 1)
	_indent = 2
	_line("return false", 1)
	_indent = 1
	_line("var m = o.get(\"__gate_impl\")", 1)
	_line("return m != null and iface in m", 1)
	_indent = saved
