# Generated by GATE from res://demo/Plain.gate - do not edit.
#
# This file is transpiled output, not source. For as long as GATE is used in
# this project, anything you change here is overwritten the next time
# res://demo/Plain.gate is compiled - edit that file instead.
#
# To stop using GATE for this script, delete this header first, then the .gate
# file; what remains is ordinary GDScript you can maintain by hand.
class_name GateDemoPlain
extends RefCounted

var value: int = 3
func doubled() -> int:
    return value * 2
