# Generated by GATE from res://demo/Weapon.gate - do not edit.
#
# This file is transpiled output, not source. For as long as GATE is used in
# this project, anything you change here is overwritten the next time
# res://demo/Weapon.gate is compiled - edit that file instead.
#
# To stop using GATE for this script, delete this header first, then the .gate
# file; what remains is ordinary GDScript you can maintain by hand.
class_name GateDemoWeapon
extends RefCounted

var damage: int = 25
var label: String = "sword"

func describe() -> String:
	return "%s (%s dmg)" % [label, damage]
