on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Build code
        run: bun run build
